# Generated by Django 4.0.5 on 2022-06-17 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeapp', '0003_alter_employee_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
