# Generated by Django 4.0.5 on 2022-06-17 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employeapp', '0005_alter_employee_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timeinout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkstate', models.BooleanField()),
                ('time', models.DateTimeField()),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='employeapp.employee')),
            ],
        ),
    ]
