# Generated by Django 4.0.5 on 2022-06-17 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employeapp', '0006_timeinout'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Timeinout',
        ),
    ]
