# Generated by Django 4.0.5 on 2022-06-20 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employeapp', '0007_delete_timeinout'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timecalc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkstate', models.IntegerField()),
                ('time', models.DateTimeField()),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='employeapp.employee')),
            ],
        ),
    ]
