# Generated by Django 4.0.5 on 2022-06-20 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeapp', '0009_alter_timecalc_checkstate_alter_timecalc_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timecalc',
            name='checkstate',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
