# Generated by Django 4.0.5 on 2022-06-24 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employeapp', '0010_alter_timecalc_checkstate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leavetype', models.CharField(blank=True, max_length=15, null=True)),
                ('time', models.CharField(blank=True, max_length=15, null=True)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='employeapp.employee')),
            ],
        ),
    ]
