# Generated by Django 4.0.5 on 2022-06-24 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeapp', '0011_leave'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
