# Generated by Django 4.0.5 on 2022-06-24 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeapp', '0013_alter_leave_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
