# Generated by Django 4.0.5 on 2022-06-24 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeapp', '0015_alter_leave_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='date',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
