# Generated by Django 4.0.5 on 2022-06-24 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employeapp', '0016_alter_leave_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leave',
            old_name='date',
            new_name='date_or_time',
        ),
        migrations.RemoveField(
            model_name='leave',
            name='time',
        ),
    ]
