# Generated by Django 4.0.5 on 2022-06-24 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employeapp', '0018_leave_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leave',
            old_name='date_or_time',
            new_name='date',
        ),
    ]
