# Generated by Django 4.0.5 on 2022-06-27 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeapp', '0019_rename_date_or_time_leave_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
