# Generated by Django 4.0.5 on 2022-06-27 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeapp', '0022_alter_leave_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
