# Generated by Django 4.0.5 on 2022-06-27 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeapp', '0023_alter_leave_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leave',
            old_name='date',
            new_name='early_logout_late_comming_time',
        ),
        migrations.RemoveField(
            model_name='leave',
            name='time',
        ),
        migrations.AddField(
            model_name='leave',
            name='system_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
