# Generated by Django 4.0.5 on 2022-06-27 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employeapp', '0024_rename_date_leave_early_logout_late_comming_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leave',
            old_name='early_logout_late_comming_time',
            new_name='date_or_time',
        ),
    ]
